import {
  auth, db, storage, signInWithEmailAndPassword, signOut, onAuthStateChanged,
  collection, addDoc, setDoc, deleteDoc, doc, onSnapshot, serverTimestamp, getDocs,
  ref, uploadBytes, getDownloadURL, deleteObject
} from './firebase-config.js';

const $ = id => document.getElementById(id);
const LOCAL_KEY = 'tk_fleet_v1';
const fields = ['vehicleNumber','vehicleName','plate','vehicleType','make','model','yearReg','assignee','status','mileage','revisionDate','insuranceDate','taxDate','serviceDate','serviceMileage','chassis','fuel','notes'];
const icons = { car:'<svg class="placeholder-car" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4"><path d="M3 14.5 5.1 9h13.8l2.1 5.5V19h-2v-2H5v2H3v-4.5Z"/><path d="M6 14h.01M18 14h.01M7 9l1.2-3h7.6L17 9" stroke-linecap="round"/></svg>' };
let vehicles = [], unsubscribe = null, pendingPhoto = '', currentUser = null;
window.firebasePortaleReady = true;

function installAuthUI() {
  const style = document.createElement('style');
  style.textContent = `.firebase-login{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:20px;background:radial-gradient(circle at 10% 8%,rgba(0,174,234,.22),transparent 31%),linear-gradient(135deg,#f5fbff,#eaf7ff 55%,#fff)}.firebase-login.hidden{display:none}.firebase-card{width:min(420px,100%);padding:32px;border:1px solid rgba(0,174,234,.35);border-radius:27px;background:rgba(255,255,255,.94);box-shadow:0 25px 70px rgba(4,74,117,.18);text-align:center}.firebase-logo{width:58px;height:58px;display:grid;place-items:center;margin:0 auto 16px;border-radius:17px;color:#fff;font-weight:950;background:linear-gradient(145deg,#00bff3,#006ba4)}.firebase-card h2{margin:0;color:#071f33;font-size:28px}.firebase-card p{margin:10px 0 20px;color:#627b8d;font-size:13px;line-height:1.55}.firebase-card input{width:100%;height:48px;margin:0 0 10px;padding:0 13px;border:1px solid rgba(0,174,234,.25);border-radius:12px;outline:0}.firebase-card input:focus{border-color:#00aeea;box-shadow:0 0 0 4px rgba(0,174,234,.08)}.firebase-card button{width:100%;height:48px;border:0;border-radius:13px;color:#fff;background:linear-gradient(135deg,#00b9ef,#006ea6);font-weight:850;cursor:pointer}.firebase-error{display:none;margin-top:12px;padding:10px;border-radius:10px;color:#ae2d3e;background:#fff0f2;font-size:11px;font-weight:750}.firebase-sync{position:fixed;left:50%;top:18px;z-index:999;display:none;transform:translateX(-50%);padding:10px 15px;border-radius:999px;color:#fff;background:#0b3148;box-shadow:0 10px 25px rgba(0,0,0,.16);font-size:11px;font-weight:800}.firebase-sync.show{display:block}`;
  document.head.appendChild(style);
  document.body.insertAdjacentHTML('afterbegin', `<div class="firebase-login" id="firebaseLogin"><form class="firebase-card" id="firebaseLoginForm"><div class="firebase-logo">TK</div><h2>Gestione mezzi</h2><p>Accedi con le stesse credenziali utilizzate per la dashboard commesse.</p><input id="firebaseEmail" type="email" autocomplete="email" placeholder="Email" required><input id="firebasePassword" type="password" autocomplete="current-password" placeholder="Password" required><button id="firebaseLoginBtn" type="submit">Accedi al gestionale</button><div class="firebase-error" id="firebaseError">Email o password non corrette.</div></form></div><div class="firebase-sync" id="firebaseSync">Sincronizzazione…</div>`);
  document.querySelector('.shell').style.display = 'none';
  const logout = document.createElement('button'); logout.className='btn btn-danger'; logout.id='firebaseLogout'; logout.textContent='Esci';
  document.querySelector('.nav-actions').appendChild(logout);
  $('firebaseLoginForm').addEventListener('submit', async e => { e.preventDefault(); const b=$('firebaseLoginBtn'); b.disabled=true; b.textContent='Accesso…'; try { await signInWithEmailAndPassword(auth,$('firebaseEmail').value.trim(),$('firebasePassword').value); $('firebaseError').style.display='none'; } catch { $('firebaseError').style.display='block'; } finally { b.disabled=false;b.textContent='Accedi al gestionale'; } });
  logout.onclick=()=>signOut(auth);
}
function sync(show=true){$('firebaseSync').classList.toggle('show',show)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function dateLabel(v){return v?new Intl.DateTimeFormat('it-IT').format(new Date(v+'T12:00:00')):'Non indicata'}
function daysUntil(v){if(!v)return Infinity;const t=new Date();t.setHours(0,0,0,0);return Math.ceil((new Date(v+'T12:00:00')-t)/86400000)}
function deadlines(v){return[['Revisione',v.revisionDate],['Assicurazione',v.insuranceDate],['Bollo',v.taxDate],['Tagliando',v.serviceDate]].filter(x=>x[1])}
function urgency(v){const ds=deadlines(v).map(x=>daysUntil(x[1]));if(ds.some(d=>d<0))return'expired';if(ds.some(d=>d<=30))return'soon';return'ok'}
function nearest(v){return deadlines(v).map(([name,date])=>({name,date,days:daysUntil(date)})).sort((a,b)=>a.days-b.days)[0]||null}
function statusClass(s){return s==='Manutenzione'?'maintenance':s==='Fermo'?'stopped':''}
function deadlineInfo(v){const n=nearest(v);if(!n)return{cls:'',text:'Nessuna scadenza inserita'};if(n.days<0)return{cls:'danger',text:`${n.name} scaduta il ${dateLabel(n.date)}`};if(n.days<=30)return{cls:'warning',text:`${n.name} tra ${n.days} giorni · ${dateLabel(n.date)}`};return{cls:'',text:`${n.name}: ${dateLabel(n.date)}`}}
function render(){const q=$('searchInput').value.trim().toLocaleLowerCase('it'),status=$('statusFilter').value,deadline=$('deadlineFilter').value;const filtered=vehicles.filter(v=>(!q||[v.vehicleNumber,v.vehicleName,v.plate,v.assignee,v.make,v.model].join(' ').toLocaleLowerCase('it').includes(q))&&(!status||v.status===status)&&(!deadline||urgency(v)===deadline));$('fleetGrid').innerHTML=filtered.length?filtered.map(v=>{const d=deadlineInfo(v),photo=v.photoData||v.photoURL;return`<article class="vehicle"><div class="vehicle-photo">${photo?`<img src="${esc(photo)}" alt="${esc(v.vehicleName)}">`:icons.car}<span class="status ${statusClass(v.status)}">${esc(v.status||'Operativo')}</span><span class="vehicle-number">N. ${esc(v.vehicleNumber||'—')}</span></div><div class="vehicle-body"><div class="vehicle-head"><h3>${esc(v.vehicleName)}</h3><span class="plate">${esc((v.plate||'').toUpperCase())}</span></div><p class="model">${esc([v.make,v.model,v.yearReg].filter(Boolean).join(' · ')||v.vehicleType||'Mezzo aziendale')}</p><div class="details"><div class="detail"><span>Assegnato a</span><strong>${esc(v.assignee||'Non assegnato')}</strong></div><div class="detail"><span>Chilometraggio</span><strong>${v.mileage?Number(v.mileage).toLocaleString('it-IT')+' km':'Non indicato'}</strong></div></div><div class="deadline ${d.cls}">${esc(d.text)}</div><div class="card-actions"><button class="btn btn-light" onclick="editVehicle('${v.id}')">Modifica</button><button class="btn btn-danger" onclick="deleteVehicle('${v.id}')">Elimina</button></div></div></article>`}).join(''):`<div class="empty">${icons.car}<h3>${vehicles.length?'Nessun mezzo trovato':'La flotta è ancora vuota'}</h3><p>${vehicles.length?'Modifica i filtri o il testo ricercato.':'Inserisci il primo mezzo aziendale: sarà salvato online e disponibile da tutti i dispositivi autorizzati.'}</p>${vehicles.length?'':'<button class="btn btn-primary" onclick="openModal()">Inserisci il primo mezzo</button>'}</div>`;updateStats()}
function updateStats(){$('totalCount').textContent=vehicles.length;$('activeCount').textContent=vehicles.filter(v=>v.status==='Operativo').length;$('expiringCount').textContent=vehicles.filter(v=>urgency(v)==='soon').length;$('expiredCount').textContent=vehicles.filter(v=>urgency(v)==='expired').length;const latest=vehicles.map(v=>v.updatedAt?.toDate?.()).filter(Boolean).sort((a,b)=>b-a)[0];$('lastUpdate').textContent=latest?new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(latest):'Archivio online connesso'}
function openModal(id){$('vehicleForm').reset();$('vehicleId').value='';$('photoData').value='';pendingPhoto='';$('photoPreview').innerHTML=icons.car;$('modalTitle').textContent='Inserisci nuovo mezzo';if(id){const v=vehicles.find(x=>x.id===id);if(!v)return;$('vehicleId').value=id;fields.forEach(f=>{if($(f)&&v[f]!=null)$(f).value=v[f]});$('modalTitle').textContent='Modifica mezzo';const photo=v.photoData||v.photoURL;if(photo)$('photoPreview').innerHTML=`<img src="${esc(photo)}" alt="Anteprima">`}$('vehicleModal').classList.add('open');$('vehicleModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>$('vehicleName').focus(),50)}
function closeModal(){$('vehicleModal').classList.remove('open');$('vehicleModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function withTimeout(promise,ms=25000){let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{const e=new Error('Il caricamento della foto ha superato il tempo massimo.');e.code='storage/timeout';reject(e)},ms)});return Promise.race([promise,timeout]).finally(()=>clearTimeout(timer))}
async function uploadPhoto(data,id){const blob=await(await fetch(data)).blob(),path=`mezzi/${id}/${Date.now()}.jpg`,photoRef=ref(storage,path);if(blob.size>5*1024*1024){const e=new Error('La foto ottimizzata supera 5 MB.');e.code='storage/file-too-large';throw e}await withTimeout(uploadBytes(photoRef,blob,{contentType:'image/jpeg'}));return{photoURL:await withTimeout(getDownloadURL(photoRef),15000),photoPath:path}}
async function deleteVehicle(id){const v=vehicles.find(x=>x.id===id);if(!v||!confirm(`Eliminare definitivamente il mezzo ${v.vehicleName} (${v.plate})?`))return;sync();try{await deleteDoc(doc(db,'mezzi',id));if(v.photoPath)await deleteObject(ref(storage,v.photoPath)).catch(()=>{});notify('Mezzo eliminato correttamente.')}catch(e){console.error(e);notify('Errore durante l’eliminazione.')}finally{sync(false)}}
function notify(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),3300)}
function firebaseError(err){const code=err?.code||'';if(code.includes('permission-denied'))return 'Permesso negato da Firestore: controlla e pubblica le Rules.';if(code.includes('storage/unauthorized'))return 'Foto non caricata: pubblica le Storage Rules e verifica che l’utente sia autenticato.';if(code.includes('storage/unauthenticated'))return 'Foto non caricata: la sessione Firebase è scaduta. Esci e accedi di nuovo.';if(code.includes('storage/bucket-not-found'))return 'Foto non caricata: il bucket Firebase Storage indicato nella configurazione non esiste.';if(code.includes('storage/quota-exceeded'))return 'Foto non caricata: quota Firebase Storage esaurita o piano di fatturazione richiesto.';if(code.includes('storage/retry-limit-exceeded')||code.includes('storage/timeout'))return 'Foto non caricata entro 25 secondi. Controlla che Firebase Storage sia attivo, poi riprova.';if(code.includes('storage/file-too-large'))return 'Foto non caricata: il file ottimizzato supera il limite di 5 MB.';if(code.includes('storage/unknown'))return 'Firebase Storage non è attivo o non è configurato correttamente.';if(code.includes('unavailable'))return 'Firebase momentaneamente non raggiungibile. Controlla la connessione.';return `Errore Firebase${code?' ('+code+')':''}: ${err?.message||'operazione non riuscita'}`}
async function migrateLocalIfNeeded(){if(localStorage.getItem(LOCAL_KEY+'_firebase_done'))return;const local=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]');if(!local.length){localStorage.setItem(LOCAL_KEY+'_firebase_done','1');return}const snap=await getDocs(collection(db,'mezzi'));if(snap.empty&&confirm(`Sono presenti ${local.length} mezzi salvati su questo dispositivo. Vuoi trasferirli ora su Firebase?`)){sync();for(const old of local){const newRef=doc(collection(db,'mezzi'));let data={...old};delete data.id;if(data.photoData){try{Object.assign(data,await uploadPhoto(data.photoData,newRef.id));delete data.photoData}catch{}}await setDoc(newRef,{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:currentUser.email,updatedBy:currentUser.email})}notify('Archivio locale trasferito su Firebase.');sync(false)}localStorage.setItem(LOCAL_KEY+'_firebase_done','1')}

installAuthUI();
onAuthStateChanged(auth,async user=>{currentUser=user;if(unsubscribe){unsubscribe();unsubscribe=null}if(!user){$('firebaseLogin').classList.remove('hidden');document.querySelector('.shell').style.display='none';vehicles=[];return}$('firebaseLogin').classList.add('hidden');document.querySelector('.shell').style.display='block';await migrateLocalIfNeeded().catch(console.error);unsubscribe=onSnapshot(collection(db,'mezzi'),snap=>{vehicles=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));render();sync(false)},e=>{console.error(e);notify(firebaseError(e));sync(false)})});
$('vehicleForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('vehicleId').value,recordRef=id?doc(db,'mezzi',id):doc(collection(db,'mezzi'));let data={};fields.forEach(f=>data[f]=$(f).value.trim());data.plate=data.plate.toUpperCase();if(vehicles.some(v=>v.id!==id&&String(v.vehicleNumber||'').toLowerCase()===data.vehicleNumber.toLowerCase()))return notify('Questo numero veicolo è già assegnato a un altro mezzo.');if(vehicles.some(v=>v.id!==id&&String(v.plate||'').toUpperCase()===data.plate))return notify('Questa targa è già presente in archivio.');if(pendingPhoto){data.photoData=pendingPhoto;data.photoURL='';data.photoPath=''}sync();try{await setDoc(recordRef,{...data,updatedAt:serverTimestamp(),updatedBy:currentUser.email,...(!id?{createdAt:serverTimestamp(),createdBy:currentUser.email}:{})},{merge:true});closeModal();notify(id?'Mezzo e fotografia aggiornati online.':'Nuovo mezzo salvato online.')}catch(err){console.error(err);notify(firebaseError(err))}finally{sync(false)}});
$('photoInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(file.size>8*1024*1024){notify('La fotografia non può superare 8 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=ev=>{const img=new Image();img.onload=()=>{const max=720,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);let quality=.64;pendingPhoto=canvas.toDataURL('image/jpeg',quality);while(pendingPhoto.length>350000&&quality>.36){quality-=.07;pendingPhoto=canvas.toDataURL('image/jpeg',quality)}if(pendingPhoto.length>500000){pendingPhoto='';e.target.value='';notify('Immagine troppo complessa: prova con una fotografia più piccola.');return}$('photoData').value=pendingPhoto;$('photoPreview').innerHTML=`<img src="${pendingPhoto}" alt="Anteprima">`};img.onerror=()=>notify('Formato immagine non leggibile.');img.src=ev.target.result};reader.readAsDataURL(file)});
['searchInput','statusFilter','deadlineFilter'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',render));$('addVehicle').onclick=()=>openModal();$('closeModal').onclick=closeModal;$('cancelModal').onclick=closeModal;$('vehicleModal').onclick=e=>{if(e.target===$('vehicleModal'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('reportButton').onclick=()=>{if(!vehicles.length)return notify('Inserisci almeno un mezzo prima del report.');$('reportDate').textContent='Generato il '+new Intl.DateTimeFormat('it-IT',{dateStyle:'long',timeStyle:'short'}).format(new Date());window.print()};$('year').textContent=new Date().getFullYear();
Object.assign(window,{openModal,editVehicle:openModal,deleteVehicle});
